project_id = "nrddbsudiphrvgfneqle"

[functions.whatsapp-instance]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.marketing-trigger]
verify_jwt = false

[functions.marketing-scheduler]
verify_jwt = false

[functions.loyalty-processor]
verify_jwt = false

[functions.payment-config]
verify_jwt = false

[functions.payment-oauth]
verify_jwt = false

[functions.payment-create]
verify_jwt = false

[functions.payment-status]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
