project_id = "nrddbsudiphrvgfneqle"

[functions.whatsapp-instance]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.marketing-trigger]
verify_jwt = false

[functions.marketing-scheduler]
verify_jwt = false

[functions.loyalty-processor]
verify_jwt = false

[functions.mercadopago-charge]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.nuvem-fiscal-company]
verify_jwt = false

[functions.nuvem-fiscal-emit]
verify_jwt = false
