// This file is automatically generated. Do not edit it directly.
// NOTE (segurança): este arquivo foi customizado. Se o Lovable regenerá-lo,
// preserve a lógica do token de sessão (Authorization Bearer) abaixo.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSessionToken } from '@/lib/authSession';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // apikey identifica o projeto (chave publishable — pública por design).
    headers.set('apikey', supabaseKey);

    // Se há um token de sessão assinado (staff/CEO logado), enviá-lo como
    // Bearer para operar como `authenticated`. Sem token, remover o
    // Authorization quando ele for apenas a chave publishable, mantendo o
    // acesso `anon` do cliente público do cardápio.
    const sessionToken = getSessionToken();
    if (sessionToken) {
      headers.set('Authorization', `Bearer ${sessionToken}`);
    } else if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get('Authorization') === `Bearer ${supabaseKey}`
    ) {
      headers.delete('Authorization');
    }

    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Sincroniza a autenticação do canal Realtime com o token de sessão vigente.
 * Necessário para receber eventos de tabelas cujo RLS exige `authenticated`.
 * Chamar após login e após logout.
 */
export function applyRealtimeAuth(): void {
  try {
    const token = getSessionToken();
    // Com token (staff/CEO) → Realtime opera como authenticated. Sem token,
    // passa `null` para o Realtime usar a apikey anônima configurada — NUNCA
    // a chave publishable como access_token (não é um JWT e quebraria o RLS).
    supabase.realtime.setAuth(token ?? null);
  } catch {
    // ignore
  }
}

// Aplica o token já existente ao carregar (ex.: refresh de página logado).
applyRealtimeAuth();
